name: vote
description: A sample command-line application.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:

  fpdart: ^1.2.0
  logger: ^2.6.2

  # Dependency injection
  get_it: ^7.7.0
  injectable: ^2.4.2

  # Codegen/serialization runtime
  freezed_annotation: 3.1.0
  json_annotation: ^4.9.0

  shared:
    path: ../shared

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

  # Codegen
  build_runner: ^2.10.1
  injectable_generator: ^2.9.0
  auto_route_generator: ^10.2.0
  freezed: ^3.2.3
  json_serializable: ^6.10.0
