name: app_theme
description: Theme micro package extracted from the Diary app.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  injectable_generator: ^2.9.0

flutter:
  uses-material-design: false
