name: shared
description: Shared utilities for the Diary app, including environment injection helpers.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  envied: ^1.3.2
  get_it: ^7.7.0
  injectable: ^2.4.2

dev_dependencies:
  build_runner: ^2.10.1
  envied_generator: ^1.3.2
  flutter_lints: ^5.0.0
