name: diary
description: "Diary App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^7.7.0
  injectable: ^2.4.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  auto_route: ^10.2.0
  uuid: ^4.5.1
  freezed_annotation: 3.1.0
  json_annotation: ^4.9.0
  drift: ^2.20.2
  drift_flutter: ^0.1.0
  sqlite3_flutter_libs: ^0.5.24
  path: ^1.9.0
  path_provider: ^2.1.4
  image: ^4.2.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  copy_with_extension_gen: ^10.0.1
  logger: ^2.6.2
  bloc_concurrency: ^0.2.5
  crypto: ^3.0.3
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.10.1
  injectable_generator: ^2.9.0
  auto_route_generator: ^10.2.0
  freezed: ^3.2.3
  json_serializable: ^6.10.0
  drift_dev: ^2.20.1

flutter:
  uses-material-design: true
