name: supabase_repository
description: A sample command-line application.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  supabase_flutter: ^2.12.0
  supabase_codegen: ^3.0.1
  envied: ^1.3.2
  get_it: ^7.7.0
  injectable: ^2.4.2

  shared:
    path: ../shared
  auth:
    path: ../auth
  vote:
    path: ../vote

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

  # Codegen
  build_runner: ^2.10.1
  envied_generator: ^1.3.2
  injectable_generator: ^2.9.0